version: '3'
services:
 nginx:
  container_name: nginx
  build: requirements/nginx/.
  depends_on:
   - wordpress
  networks:
   - shared-network
  volumes:
   - wp_data:/var/www/html 
  ports :
   - "443:443"
   - "9000"



 mariadb:
  container_name: mariadb
  build: 
    context: requirements/mariadb/.
    args:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOTUSER: ${DB_ROOTUSER}
      DB_ROOTPASS: ${DB_ROOTPASS}
  networks:
   - shared-network
  ports:
    - 3306


 wordpress:
  container_name: wordpress
  depends_on:
    - mariadb
  env_file: .env
  build: 
    context: requirements/wordpress/.
    args:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOTUSER: ${DB_ROOTUSER}
      DB_ROOTPASS: ${DB_ROOTPASS}
      WP_PATH: ${WP_PATH}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_PASS: ${WP_PASS}
      WP_USER: ${WP_USER}
      WP_USERPASS: ${WP_USERPASS}
      WP_EMAIL: ${WP_EMAIL}
      WP_URL: ${WP_URL}
  volumes:
    - wp_data:/var/www/html
  depends_on:
   - mariadb
  networks:
   - shared-network
  ports :
   - "9000"
networks:
 shared-network: {}

volumes:
    wp_data:
      driver_opts:
        type: local
        device: /home/rsaf/data/wp_files
        o: bind
    db_data:
      driver_opts:
        type: local
        device: /home/rsaf/data/wp_database

