version: '3'
services:
 nginx:
  container_name: nginx
  image : nginx
  build: requirements/nginx/.
  depends_on:
   - wordpress
  networks:
   - frontend-network
  restart: on-failure
  volumes:
   - wp_data:/var/www/html 
  ports :
   - "443:443"



 mariadb:
  container_name: mariadb
  image : mariadb
  build: 
    context: requirements/mariadb/.
    args:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOTUSER: ${DB_ROOTUSER}
      DB_ROOTPASS: ${DB_ROOTPASS}
  volumes:
    - db_data:/var/lib/mysql
  networks:
   - backend-network
  restart: on-failure
  ports:
    - 3306


 wordpress:
  container_name: wordpress
  image : wordpress
  depends_on:
    - mariadb
  env_file: .env
  build: 
    context: requirements/wordpress/.
    args:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_ROOTUSER: ${DB_ROOTUSER}
      DB_ROOTPASS: ${DB_ROOTPASS}
      WP_PATH: ${WP_PATH}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN: ${WP_ADMIN}
      WP_PASS: ${WP_PASS}
      WP_USER: ${WP_USER}
      WP_USERPASS: ${WP_USERPASS}
      WP_EMAIL: ${WP_EMAIL}
      WP_URL: ${WP_URL}
  volumes:
    - wp_data:/var/www/html
  depends_on:
   - mariadb
  networks:
   - frontend-network
   - backend-network
  restart: on-failure
  ports :
   - "9000"
networks:
 frontend-network: {}
 backend-network: {}


volumes:
    wp_data:
      driver_opts:
        type : bind
        device: /home/rsaf/data/wp_files
        o: bind
    db_data:
      driver_opts:
        type: bind
        device: /home/rsaf/data/wp_database
        o: bind

