version: '3'
services:
 nginx:
  container_name: nginx
  build: nginx/.
  networks:
   - shared-network
  ports :
   - "443:443"



 mariadb:
  container_name: mariadb
  build: mariadb/.
  networks:
   - shared-network
  ports:
    - 3306


 wordpress:
  container_name: wordpress
  depends_on:
    - mariadb
  build: wordpress/.
  volumes:
    - wp_data:/var/www/html
  depends_on:
   - mariadb
  networks:
   - shared-network
  ports :
   - "9000"

networks:
 shared-network: {}

volumes:
    wp_data:
      driver_opts:
        type: local
        device: /home/rsaf/data
        o: bind
