
services:
	nginx:
		build: /nginx/.
		image: nginx
		networks:
			- shared-network
		port :
			-	"443:443"
	mariadb:
		build: /mariadb/.
		image: mariadb
		networks:
			- shared-network
	wordpress:
		build: /wordpress/.
		image: wordpress
		networks:
			- shared-network
		port :
			- 9000

networks:
	shared-network: {}