CREATE DATABASE IF NOT EXISTS _DataBase;
CREATE USER IF NOT EXISTS _userRsaf IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON _DataBase.* TO _userRsaf;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';
USE _DataBase;
CREATE TABLE _Users (Login VARCHAR(100), Name VARCHAR(100)); 
FLUSH PRIVILEGES;
