CREATE DATABASE IF NOT EXISTS db;
CREATE USER IF NOT EXISTS rsaf IDENTIFIED BY 'rsaf';
GRANT ALL PRIVILEGES ON db.* TO rsaf;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';
USE db;
CREATE TABLE _Users (Login VARCHAR(100), Name VARCHAR(100)); 
FLUSH PRIVILEGES;
