CREATE DATABASE IF NOT EXISTS _DataBase;
CREATE USER IF NOT EXISTS _userRsaf IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON _DataBase.* TO _userRsaf;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root';
FLUSH PRIVILEGES;
